### PR TITLE
Adding fact about double engine trains

### PR DESCRIPTION
**Pull request by dalanmiller**
Just learned this fact and thought it would be a worthy addition here!

### CODE REVIEW

**Comment by DDDGamer** [comment]
Source? Adding a Loco at the end i though counts as 2 cargo wagons

**Comment by jlogsdon** [comment]
Perhaps the missing context is "facing in the same direction". All trains facing "forward" with fuel are used, so a 1-4-1 with both engines facing the same direction has the same acceleration as a 2-4.

**Comment by dalanmiller** [comment]
> Perhaps the missing context is "facing in the same direction". All trains facing "forward" with fuel are used, so a 1-4-1 with both engines facing the same direction has the same acceleration as a 2-4.

@jlogsdon yes! 

Can you confirm that with all engines facing the same direction, the acceleration of a train of 2 engines and N cars is greater than 1 engine and N cars with the same top speed?

**Comment by jlogsdon** [comment]
I'll run a quick test tonight but it should be the same as 2 engines on the front, which definitely improves acceleration.

**Comment by dalanmiller** [comment]
I guess what we really should be looking for here, is the equation to maximize speed or maximize acceleration per ratio of FF (forward facing) engines to fluid cars or solids cars.

**Comment by DDDGamer** [comment]
I think its intuitive that adding more engines in same direction will improve acceleration, so i dont see a need to explicitly say that in the cheat sheet. On the other hand if as @dalanmiller mentioned, a formula for diminishing returns would be neat. Though i do have it mentioned that "Trains with ratio of 1:2 will not experience a decrease in max speed" So  that actually seems the sweet spot.
There are already common existing setups, most people will be using the 1-2-1 or 2-4-2 trains as this is fine for majority of the gameplay.

**Pull request closed without merging**
